### PR TITLE
Emboldened important text

### PR DESCRIPTION
**Pull request by AntsyBoi**
Emboldened all YMMVs and the first half of the disclaimer at the bottom to better show risks of using it / uncertainties with it's capabilities outside of it's intended already very experimental range.

### CODE REVIEW

**Comment by badabing2005** [comment]
Thanks for your contributions.
This is how it looks in your repo, I doubt that you intended this
see:
```
**```text
```

image

**Comment by AntsyBoi** [comment]
I fixed the given error and will be pushing a new commit with it soon. What program are you using to preview the md as I see it like this:
image
And your preview is this:
image
I'm not talking about the themes but rather how it formats multiline code snippets and emboldens text within them.

**Comment by badabing2005** [comment]
> 

Just go here and scroll down.
https://github.com/AntsyBoi/PixelFlasher/tree/patch-1

**Comment by AntsyBoi** [comment]
Should be fixed now

**Comment by badabing2005** [comment]
> Should be fixed now
Don't remove the language `text`
See [md040](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md040)

**Comment by AntsyBoi** [comment]
I added it back, is it good to merge?

**Comment by badabing2005** [comment]
Honestly though, **YMMV** being bold feels out of place, It takes all of the focus.
That is not the intent of the document, yes I understand the disclaimer and all, but it does not have to be bold, look at the bright side, it is not in fine print either like in so many disclaimers.
I think I'll leave it as is.

image

**Pull request closed without merging**
