### PR TITLE
Add a link to TrickyStore Github page

### PR DESCRIPTION
**Pull request by VisionR1**
Added link for Tricky Store.

### CODE REVIEW

**Comment by badabing2005** [comment]
There is a better option already in PF.
Do we also need a link?
image
image
image

**Comment by VisionR1** [comment]
> There is a better option already in PF. Do we also need a link? image image image

How did I not see that?
Sorry.
I'm on A11.
But i think is good to added the main threads, like you have with guide.

**Comment by badabing2005** [comment]
The links predate the install option, in any case I'll add the TS link, it doesn't hurt.

**Comment by VisionR1** [comment]
> The links predate the install option, in any case I'll add the TS link, it doesn't hurt.

Thanks.
I noticed the TrickyStore is in the Pif modules, according to some new info is more bootloader & keybox spoofing. 
I have change and the title. 
You can see the last pages on XDA.

**Comment by badabing2005** [comment]
I realized that, but don't feel like creating a separate button for it
I'll rename the main button to `Install Pif / TS module`

**Comment by badabing2005** [comment]
Thanks.
Link is in.

**Pull request closed without merging**
